############################## 项目启动信息配置 开始  ##############################
server:
  port: 8080
############################## 项目启动信息配置 结束  ##############################
############################## spring配置 开始  ##############################
spring:
  profiles:
    active: dev                            # 当前激活的配置文件
  mvc:
    static-path-pattern: /static/**         # 静态资源路径
    view:
      prefix: /view/                 # 页面文件路径
  resources:
    static-locations: /static,classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources #静态资源访问
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  velocity:
    enabled: true
    resource-loader-path: classpath:/templates/
    suffix: .vm
  thymeleaf:
    cache: false
    prefix: /view/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
############################## spring配置 结束  ##############################
#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:com/**/mapping/*.xml
  typeAliasesPackage: com.xxxx.**.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /login/getCode
    - /resources/**
    - /static/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
    - /**
